-- WFH vs. On-Site Conditional Aggregation (1.26.2) - Problem
-- 1.26 CASE Expression
-- Problem Statement
-- From the data_jobs database, calculate and return a single row that shows the count of unique companies offering Work From Home (WFH) jobs versus the count of unique companies offering Non-WFH jobs.


USE data_jobs;

SELECT
    COUNT(DISTINCT CASE WHEN jpf.job_work_from_home = TRUE THEN company_id END) AS wfh_companies,
    COUNT(DISTINCT CASE WHEN jpf.job_work_from_home = FALSE THEN company_id END) AS non_wfh_companies
FROM job_postings_fact AS jpf;

/*
Connect to data_jobs: duckdb md:data_jobs opens a DuckDB session pointing at the shared data_jobs database so all queries run against that dataset.
Conditional Counting (The 'Why'): This query uses a CASE expression directly within the COUNT aggregate function to achieve conditional aggregation. This allows the query to count records that satisfy a specific condition without needing a WHERE clause or GROUP BY to separate the counts. The entire aggregation happens in a single row.

Counting WFH Companies:
COUNT(DISTINCT CASE WHEN jpf.job_work_from_home = TRUE THEN company_id END) AS wfh_companies:
The CASE expression returns the company_id only if the job offers remote work (job_work_from_home is TRUE); otherwise, it returns NULL (the implicit ELSE).
The COUNT(DISTINCT ...) function then counts every unique, non-NULL company_id that was generated by the CASE statement, effectively counting only companies that offer remote work.
Counting Non-WFH Companies:
COUNT(DISTINCT CASE WHEN jpf.job_work_from_home = FALSE THEN company_id END) AS non_wfh_companies:
This logic is identical to the first, but it only returns the company_id when the job is explicitly not remote (job_work_from_home is FALSE), counting only companies offering on-site work.
DISTINCT Note: Using DISTINCT inside the COUNT ensures that if a single company has multiple job postings (some remote and some not), that company is counted only once in the final total for each category.
*/